version: '3'

services:
  app:
    container_name: app_node
    build: 
      context: ./node
    ports:
      - 3000:3000
    networks:
      - mynetwork
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
      
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
      - MYSQL_PASSWORD=root
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - mynetwork
    tty: true

  nginx:
    build:
      context: ./nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - mynetwork
    tty: true
    depends_on:
      - app

networks:
  mynetwork:
    driver: bridge

  