apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: pliniopba/hello-go:v6
        startupProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 3
            failureThreshold: 10
        readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            failureThreshold: 1
            periodSeconds: 3
#            initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1
#         initialDelaySeconds: 10
        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: secret-user
        volumeMounts:
        - name: config
          mountPath: /go/myfamily
      volumes:
      - name: config
        configMap:
          name: configmap-family
          items:
            - key: members
              path: family.txt
        #env:
        #  - name: NAME
        #    valueFrom:
        #      configMapKeyRef:
        #        name: goserver-env
        #        key: NAME
        #  - name: AGE
        #    valueFrom:
        #      configMapKeyRef:
        #        name: goserver-env
        #        key: AGE